export const AREAS = {
  auth: ["login", "logout", "register", "reset-password", "zero-friction-redirect", "launch"],
  account: [
    "account-page",
    "account-beta-page",
    "account-edit-page",
    "account-import-page",
    "remove-device-data",
    "beta-channel",
  ],
  log: [
    "log-page",
    "log-page-boot-perf",
    "entries-table-collapse",
    "entries-table-headers",
    "table-toolbar",
    "status-carousel",
    "status-icons",
    "narrow-layout",
    "overlay-scroll",
  ],
  view: ["view-page", "profile-page", "demo-visit", "component-harnesses"],
  performance: [
    "performance-page",
    "performance-pyramid-page",
    "performance-gap-page",
    "performance-injury-page",
    "performance-rpe-page",
    "performance-strengths-page",
    "performance-trends-page",
    "performance-on-device",
    "reports-on-device",
    "component-harnesses",
  ],
  sync: ["sync-page", "queue-replay", "offline-launch", "entries-cache", "per-user-data", "asset-caching"],
  tour: ["tour", "welcome", "demo-visit"],
  admin: ["admin"],
  reports: ["report-and-hide", "report-issue-page", "feedback-page"],
  chrome: ["climbing-header", "landmarks", "accessibility", "apex-links"],
};
