// The owner app's shell only; data is never cached here (docs/app-architecture.md, Offline and sync).
import { classifyRequest, LAUNCH_PATH } from "./classify.js";
import { cacheNameFor, cachesToDelete } from "./caches.js";
import { isCacheableAsset, isCacheableShell, shellCacheKey } from "./responses.js";
import { fillPrecache, precacheUsername } from "./precache.js";

/* global __BUILD_ID__, __PRECACHE__ */
const BUILD_ID = __BUILD_ID__;
const CACHE_NAME = cacheNameFor(BUILD_ID);
// ignoreVary: pre-cached copies have no Origin, so CORS requests (modules, fonts) wouldn't match.
const MATCH = { ignoreVary: true };

// { shells: [{ page, hash }], assets: [{ url, hash? }] }, generated by the
// build (#948, scripts/precache-list.mjs).
const PRECACHE = __PRECACHE__;

self.LOGBOOK_BUILD = Object.freeze({ id: BUILD_ID, cacheName: CACHE_NAME, precache: PRECACHE });

// The owner of an open owner page; if none, shells wait for the next precache message.
async function ownerUsername() {
  const windows = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
  for (const client of windows) {
    const username = precacheUsername(client.url);
    if (username) return username;
  }
  return null;
}

// One fill at a time: a second request while one runs shares it.
let filling = null;
function precache(username) {
  filling ??= fillPrecache({ list: PRECACHE, cacheName: CACHE_NAME, origin: self.location.origin, username })
    .finally(() => { filling = null; });
  return filling;
}

self.addEventListener("install", event => {
  // A new build takes over as soon as it's installed; pages pick up its
  // shells on their next launch (no forced reload, ADR-0028 decision 6).
  self.skipWaiting();
  // Installed only when complete; a retry fetches only what's missing.
  event.waitUntil((async () => {
    const { missing } = await precache(await ownerUsername());
    if (missing.length) throw new Error(`pre-cache incomplete: ${missing.length} item(s) missing`);
  })());
});

// Tops up what this build's cache lacks, such as shells after a logout.
self.addEventListener("message", event => {
  if (event.data?.type !== "precache") return;
  const username = event.source?.url ? precacheUsername(event.source.url) : null;
  event.waitUntil(precache(username));
});

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    // Keep this build's cache and the previous build's (an open tab from
    // the last build keeps finding its assets); drop the rest.
    const stale = cachesToDelete(await caches.keys(), CACHE_NAME);
    await Promise.all(stale.map(name => caches.delete(name)));
    await self.clients.claim();
  })());
});

async function put(request, response) {
  const cache = await caches.open(CACHE_NAME);
  await cache.put(request, response);
}

// No revalidation: shells change only with the build.
async function ownerShell(event, page) {
  const key = shellCacheKey(page, self.location.origin);
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(key, MATCH);
  if (cached) return cached;
  const response = await fetch(event.request);
  if (isCacheableShell(response, page)) event.waitUntil(cache.put(key, response.clone()));
  return response;
}

// The installed app's start page (#949): cache-first from this build's
// cache, like a shell -- it only changes when the build does.
async function launchPage(event) {
  const key = new URL(LAUNCH_PATH, self.location.origin).href;
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(key, MATCH);
  if (cached) return cached;
  const response = await fetch(event.request);
  if (isCacheableAsset(response) && !response.redirected) event.waitUntil(cache.put(key, response.clone()));
  return response;
}

// Content-addressed: the URL changes whenever the content does, so any
// cached copy (this build's or the previous one's) is right forever.
async function immutable(event) {
  const cached = await caches.match(event.request, MATCH);
  if (cached) return cached;
  const response = await fetch(event.request);
  if (isCacheableAsset(response)) event.waitUntil(put(event.request, response.clone()));
  return response;
}

// Fonts have an unversioned URL: serve the cached copy straight away and
// refresh it in the background.
async function staleWhileRevalidate(event) {
  const cached = await caches.match(event.request, MATCH);
  const refresh = fetch(event.request).then(response => {
    if (isCacheableAsset(response)) return put(event.request, response.clone()).then(() => response);
    return response;
  });
  if (cached) {
    event.waitUntil(refresh.catch(() => {}));
    return cached;
  }
  return refresh;
}

// Other /-/ static files (icons, manifest, world-map data): the
// network when there is one, the last good copy when there isn't.
async function networkFirst(event) {
  try {
    const response = await fetch(event.request);
    if (isCacheableAsset(response)) event.waitUntil(put(event.request, response.clone()));
    return response;
  } catch (err) {
    const cached = await caches.match(event.request, MATCH);
    if (cached) return cached;
    throw err;
  }
}

self.addEventListener("fetch", event => {
  const { request } = event;
  const route = classifyRequest({ url: request.url, method: request.method, mode: request.mode, workerOrigin: self.location.origin });
  switch (route.kind) {
    case "owner-shell": return event.respondWith(ownerShell(event, route.page));
    case "launch": return event.respondWith(launchPage(event));
    case "immutable": return event.respondWith(immutable(event));
    case "font": return event.respondWith(staleWhileRevalidate(event));
    case "static": return event.respondWith(networkFirst(event));
    default: return; // passthrough: the browser handles it as if there were no worker
  }
});
